### ISSUE TITLE
Build 12 commands not registering

### ISSUE THREAD

**Issue by leafeven** [sharkbound/AdminWarnings#1]
Unturned version 3.17.5.2
rocket version: 1065

the warn command isn't registering when the plugin is loading, output from server console is below 

```
[loading] AdminWarnings[registered] /removewarn (AdminWarnings.CommandRemoveWarn/removewarn)
[registered] /warns (AdminWarnings.CommandWarnings/warns)
AdminWarnings >> AdminWarnings has Loaded!
```

**Comment by sharkbound** [comment]
is it enabled in Commands.config.xml in the rocket directory?

**Comment by leafeven** [comment]
yes, it and i can issue commands /removewarn (of which there are none) and /warns it tells me there are 0 warns for me. so it seams like its working except for the warn command is command not found

**Comment by sharkbound** [comment]
try deleting Commands.config.xml, deleting it and letting it regen often solves these issues

**Comment by leafeven** [comment]
That was the issue, there was an old plugin in there that had warn assigned to it.
